name: 生成TWRP设备树

on:
  workflow_dispatch:
    inputs:
      PY:
        description: 'Python3版本（推荐3.6/3.9）'
        required: true
        default: '3.9'
      IMG:
        description: 'IMG直链'
        required: true
        default: ''
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: 准备环境
        run: |
          sudo apt update
          sudo apt -y install cpio wget

      - name: 准备Python3
        uses: actions/setup-python@v4
        with:
          python-version: ${{ github.event.inputs.PY }}
          cache: 'pip'
          
      - name: 准备TWRP生成器 
        run: pip3 install -r requirements.txt
        
      - name: 下载
        run: wget ${{ github.event.inputs.IMG }}
        
      - name: 执行
        run: |
          ls
          mkdir dt
          python3 -m twrpdtgen -o dt/ *.img
          
      - name: 打压缩包
        run: |
          ls
          zip -r DeviceTree.zip ./dt
          ls
      - name: 完成发布
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./DeviceTree.zip
          name: TWRP_Device_Tree-${{ github.run_id }}
          tag_name: ${{ github.run_id }}
          body: DeviceTree for TWRP
