name: 生成TWRP设备树

on:
  workflow_dispatch:
    inputs:
      PY:
        description: 'Python3版本（推荐3.6/3.9）'
        required: true
        default: '3.9'
      IMG:
        description: 'IMG直链'
        required: true
        default: 'Initboot.img'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4

      - name: 准备环境
        run: |
          sudo apt update
          sudo apt -y install cpio wget

      - name: 准备Python3
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.PY }}
          cache: 'pip'

      - name: 准备TWRP生成器 
        run: pip3 install -r twrpdtgen       


      - name: 执行
        run: |
          mkdir out
          python3 -m twrpdtgen -o ./out/ ./${{ github.event.inputs.IMG }}

      - name: 打压缩包
        run: |
          ls
          cd ./out
          echo "开始打包"
          zip -r -9 ../TWRP_Device_Tree-${{ github.run_id }}.zip ./*
          ls
      - name: 上传
        uses: actions/upload-artifact@main
        with:  
          name: TWRP_Device_Tree-${{ github.run_id }}  
          path: ./out/*

      - name: 配置上传会话
        uses: lhotari/action-upterm@v1
        with:
          ## limits ssh access and adds the ssh public key for the user which triggered the workflow
          limit-access-to-actor: true
          ## limits ssh access and adds the ssh public keys of the listed GitHub users
          limit-access-to-users: peter-tank
        ## If no one connects after 10 minutes, shut down server.
          wait-timeout-minutes: 10

      - name: 上传到发布
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./TWRP_Device_Tree-${{ github.run_id }}.zip
          name: TWRP_Device_Tree-${{ github.event.inputs.IMG }}
          tag_name: ${{ github.run_id }}
          body: DeviceTree for twrp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     

      ##- name: Release
      ##  uses: softprops/action-gh-release@v1
      ##  env:  
      ##    GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      ##  with:
      ##    files: ./TWRP_Device_Tree-${{ github.run_id }}.zip
      ##    name: TWRP_Device_Tree-${{ github.run_id }}
      ##    tag_name: ${{ github.run_id }}
      ##    body: TWRP设备树-${{ github.event.inputs.IMG }}
      ##    draft: true

      - name: 清理编译流程  
        uses: Mattraks/delete-workflow-runs@main
        with:  
          retain_days: 0  
          keep_minimum_runs: 2
